POST http://127.0.0.1:8000/api/v1/assignment-students
Accept: application/json
Authorization: Bearer 9|RPzm8V9ZBK9IiLvdpgPh0Whca4xdROr2SyQvTzV37e00f32f
Content-Type: multipart/form-data; boundary=----MyBoundary

----MyBoundary
Content-Disposition: form-data; name="assignment_id"

1
----MyBoundary
Content-Disposition: form-data; name="student_id"

2
----MyBoundary--
